name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a clear and concise description of what the bug is.
      placeholder: >
        Tell us a description of the bug.
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide details of how to reproduce the bug.
      placeholder: >
        ex. 1. Go to '...'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: >
        ex. I expected '...' to happen
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What did actually happen?
      placeholder: >
        ex. Instead '...' happened
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
      default: 0
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: Which version of Python are you using?
      options:
        - Python 3.12
        - Python 3.11
        - Python 3.10
        - Python 3.9
        - Python 3.8
        - Python 3.7
        - Python 3.6
        - Python 3.5
      default: 1
    validations:
      required: true
  - type: dropdown
    id: Pyrgg-version
    attributes:
      label: Pyrgg version
      description: Which version of Pyrgg are you using?
      options:
        - Pyrgg 1.4
        - Pyrgg 1.3
        - Pyrgg 1.2
        - Pyrgg 1.1
        - Pyrgg 1.0
        - Pyrgg 0.9
        - Pyrgg 0.8
        - Pyrgg 0.7
        - Pyrgg 0.6
        - Pyrgg 0.5
        - Pyrgg 0.4
        - Pyrgg 0.3
        - Pyrgg 0.2
        - Pyrgg 0.1
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
