{% set name = "pyrgg" %}
{% set version = "1.4" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/sepandhaghighi/pyrgg
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.5
    run:
        - art >=0.7
        - pyyaml >=3.12
        - python >=3.5
about:
    home: https://github.com/sepandhaghighi/pyrgg
    license: MIT
    license_family: MIT
    summary: Python Random Graph Generator
    description: |
        PyRGG is a user-friendly synthetic random graph generator that is written in Python and supports multiple graph file formats, such as DIMACS-Graph files. It can generate graphs of various sizes and is specifically designed to create input files for a wide range of graph-based research applications, including testing, benchmarking, and performance analysis of graph processing frameworks. PyRGG is aimed at computer scientists who are studying graph algorithms and graph processing frameworks.

        Website: https://www.pyrgg.ir

        Repo: https://github.com/sepandhaghighi/pyrgg
extra:
    recipe-maintainers:
        - sepandhaghighi
