# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

env:
  TEST_PYTHON_VERSION: 3.9
  TEST_OS: 'ubuntu-20.04'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macOS-13]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0, 3.11.0, 3.12.0, 3.13.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installation
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: First test
      run: |
        pyrgg test
        pyrgg --version
    - name: Test requirements Installation
      run: |
        python otherfile/requirements-splitter.py
        pip install --upgrade --upgrade-strategy=only-if-needed -r test-requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest test --cov=pyrgg --cov-report=term
    - name: Version check
      run: |
        python otherfile/version_check.py
      if: matrix.python-version == env.TEST_PYTHON_VERSION
    - name: Other tests
      run: |
          python -m vulture pyrgg/ otherfile/ setup.py --min-confidence 65 --exclude=__init__.py --sort-by-size
          python -m bandit -r pyrgg -s B311,B403
          python -m pydocstyle -v --match-dir=pyrgg
      if: matrix.python-version == env.TEST_PYTHON_VERSION
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          fail_ci_if_error: false
      if: matrix.python-version == env.TEST_PYTHON_VERSION && matrix.os == env.TEST_OS
    - name: cProfile - PyRGG Engine
      run: |
          python -m cProfile -s cumtime otherfile/profiles/pyrgg_profile.py
    - name: cProfile - Erdos Reyni Gilbert Engine
      run: |
          python -m cProfile -s cumtime otherfile/profiles/erg_profile.py
    - name: cProfile - Erdos Reyni Engine
      run: |
          python -m cProfile -s cumtime otherfile/profiles/er_profile.py
